pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Deploy') {
            steps {
                sshagent(['ssh-key']) {
                    sh 'ssh -tt StrictHostKeyChecking=no root@8.219.41.186 ls'
                }
            }
        }
    }
}