node {
    stage('Build') {
        docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
            sh 'mvn -B -DskipTests clean package'
        }
    }

    stage('Test') {
        docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2') {
            sh 'mvn test'
        }
        // Post-action untuk selalu mengarsipkan laporan JUnit
        junit 'target/surefire-reports/*.xml'
    }

    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?', ok: 'Lanjut'
    }

    stage('Deploy') {
        sh './jenkins/scripts/deliver.sh'
        sleep 60
    }
}
