pipeline {
 
    agent {
 
        docker {
 
            image 'maven:3.9.0'
 
            args '-v /root/.m2:/root/.m2'
 
        }
 
    }
 
    stages {
 

        stage('Deploy') {
 

        stage('Build') {
 

            steps {
 

                sh 'mvn -B -DskipTests clean package'
 

            }
 

        }
 

        stage('Test') {
 
            steps {
 

                script {
 

                    sshagent(['ssh-key']) {
 

                    sh 'ssh -o StrictHostKeyChecking=no root@8.219.41.186 ls'
 

                    }
 

                sh 'mvn test'
 

            }
 

            post {
 

                always {
 

                    junit 'target/surefire-reports/*.xml'
 
                }
 
            }
 
        }
 

        stage('Manual Approval') {
 

            steps {
 

                input 'Lanjutkan ke tahap Deploy?'
 

            }    
 

        }
 

        stage('Deploy') {
 

            steps {
 

                sh './jenkins/scripts/deliver.sh'
 


 

                sleep 60 
 

            }
 

        }
 
    }
 
}